### ISSUE TITLE
Error on Windows because patterns depend on the underlying platform's path separator

### ISSUE THREAD

**Issue by jaredkrinke** [webketje/metalsmith-taxonomy#14]
Note: this is a minor issue (but I thought I'd file so others can search for and find the error message).

Repository to reproduce the error on Windows is here:
https://github.com/jaredkrinke/metalsmith-taxonomy-test

When building with Metalsmith on Windows, the native path separator is used to identify files in the `files` collection, e.g. "posts\test.md" (instead of "posts/test.md", as you'd see for POSIX). This probably breaks metalsmith-taxonomy when building on both platforms with identical code. The error is below, but it's basically saying "the matched file path isn't a key on `files`" (which is true because the path separators don't exactly match):

```
TypeError: Cannot read property 'category' of undefined
    at C:\Users\jared\Code\metalsmith-taxonomy-test\node_modules\metalsmith-taxonomy\lib\taxonomy-set.js:77:18
    at C:\Users\jared\Code\metalsmith-taxonomy-test\node_modules\metalsmith-taxonomy\lib\index.js:88:24
    at Array.forEach (<anonymous>)
    at C:\Users\jared\Code\metalsmith-taxonomy-test\node_modules\metalsmith-taxonomy\lib\index.js:85:27
    at Array.forEach (<anonymous>)
    at C:\Users\jared\Code\metalsmith-taxonomy-test\node_modules\metalsmith-taxonomy\lib\index.js:80:36
    at Array.forEach (<anonymous>)
    at Ware.plugin (C:\Users\jared\Code\metalsmith-taxonomy-test\node_modules\metalsmith-taxonomy\lib\index.js:67:18)
    at Ware.<anonymous> (C:\Users\jared\Code\metalsmith-taxonomy-test\node_modules\wrap-fn\index.js:45:19)
    at Immediate.next (C:\Users\jared\Code\metalsmith-taxonomy-test\node_modules\ware\lib\index.js:85:20)
```

In this case (repository linked above), I'm using the default options (so "**/*.{md,html}") and I get the error above when building on Windows. If I change the pattern to "**\\*.{md,html}", then it builds fine on Windows. I *suspect* (but have not confirmed) that would then break on Linux.

Ideally, the same pattern (especially the default pattern) should work on any platform.

Fortunately, this issue is easily worked around by just adding another plugin to normalize slashes to "/".

For what it's worth, I'd argue that the multimatch behavior here is the correct behavior. It's debatable if a fix would be more appropriate in this plugin or Metalsmith itself, but I'd lean toward this plugin, since I haven't encountered this sort of problem with other plugins I've used (e.g. the "root path" plugin handles Windows fine).

And one last note: thanks for sharing this plugin! I had a custom plugin to do something similar, but this is a much more general design (and it includes some features I hadn't thought of). Nice work!

**Comment by webketje** [comment]
@jaredkrinke thanks for reporting and you're welcome.

In release 0.4.0 I switched multimatch to micromatch, as perf benchmarks indicated it was up to 10x faster, see https://github.com/segmentio/metalsmith/issues/338#issuecomment-790111326. But it seems I overlooked an important note about about backslashes: https://github.com/micromatch/micromatch#backslashes (micromatch strictly adheres to bash standards and considers `\` an escape character). 

However, according to the micromatch docs, the `options.posixSlashes` should be set to true on Windows by default so you shouldn't encounter this issue in the first place. I will come back to this issue shortly as I was hoping to use micromatch in metalsmith core and need to guarantee backwards-compatibility.

**Comment by webketje** [comment]
@jaredkrinke it should be fixed in master, but Travis CI build is failing on Windows.. not sure why.
If you have some time, could you clone this repository & run `npm install` and `npm test` and report how many tests failed & which node version you used?

**Comment by jaredkrinke** [comment]
Sure, and thanks for fixing the bug (I just checked and it's fixed on master):


[results.txt](https://github.com/webketje/metalsmith-taxonomy/files/7759929/results.txt)

**Comment by webketje** [comment]
@jaredkrinke my previous fix was no good. The issue was not in the `windows` option but the fact that micromatch normalizes returned paths to use forward slashes only, and only accepts forward slashes as path separator as input. With the new fix you should be able to use both forward and backslash
